DELIMITER //
CREATE PROCEDURE EJ1()
   BEGIN
   DECLARE NUM INT default 1;
   DECLARE RES Varchar(50) default '';
   SET RES = '';
   WHILE NUM <=10 DO
	   SET RES = CONCAT(RES, NUM, ',');
	   SET NUM = NUM + 1;
   END WHILE;
   SELECT RES;
END //

CALL EJ1; --LLAMAR A LA FUNCIÓN
DROP PROCEDURE EJ1; --ELIMINAR LA FUNCIÓN

