CREATE DATABASE BASE1;
USE BASE1;
SET GLOBAL local_infile = 1;
SET GLOBAL interactive_timeout = 300;

CREATE TABLE FLORES(LGTALLO FLOAT NOT NULL, ANTALLO FLOAT NOT NULL, LGPETALO FLOAT NOT NULL, ANPETALO FLOAT NOT NULL, ESPECIE TEXT NOT NULL) ENGINE = CSV;
SHOW VARIABLES LIKE 'local_infile';

#COPIE EL ARCHIVO EN
SHOW VARIABLES LIKE 'secure_file_priv';

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/iris.csv'
INTO TABLE FLORES
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '\\'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SELECT * FROM FLORES;

#Mover el archivo al directorio de trabajo
SELECT * FROM FLORES
INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/flores_export.csv'
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';