FROM neo4j:latest
#Usuario por defecto: neo4j
#Contraseña: contrasena123
ENV NEO4J_AUTH=neo4j/contrasena123
# Exponer los puertos para el protocolo Bolt y la interfaz web
EXPOSE 7474 7687

#docker build -t neo4jimg .
#docker run -p 7474:7474 -p 7687:7687 -d neo4jimg

#http://localhost:7474/browser/