CREATE DATABASE EJEMPLO_3;
USE EJEMPLO_3;
CREATE TABLE Tabla1(ID INT NOT NULL AUTO_INCREMENT, GRUPO TEXT, 
ASISTENCIA INT, NOTA REAL,
PRIMARY KEY (ID));
INSERT INTO Tabla1(GRUPO, ASISTENCIA, NOTA) VALUES ('GRUPO1', 2, 3.2);
INSERT INTO Tabla1(GRUPO, ASISTENCIA, NOTA) VALUES ('GRUPO2', 5, 2.8);
INSERT INTO Tabla1(GRUPO, ASISTENCIA, NOTA) VALUES ('GRUPO3', 1, 1.2);
INSERT INTO Tabla1(GRUPO, ASISTENCIA, NOTA) VALUES ('GRUPO1', 5, 3.2);
INSERT INTO Tabla1(GRUPO, ASISTENCIA, NOTA) VALUES ('GRUPO3', 3, 3.2);
SELECT *FROM Tabla1;
#Dato unico con menor nota
SELECT GRUPO, MIN(NOTA) AS DEFINITIVA FROM Tabla1 ORDER BY NOTA;
#Datos unicos con mayor nota
SELECT GRUPO, MAX(NOTA) AS DEFINITIVA FROM Tabla1 GROUP BY GRUPO;
#Caracteristicas combinadas
SELECT GRUPO, MAX(NOTA) AS DEFINITIVA FROM Tabla1 GROUP BY GRUPO ORDER BY DEFINITIVA;
#Actualizar uno o varios registros
UPDATE Tabla1 SET ASISTENCIA=0 WHERE ID=2;
#Borrar registro
DELETE FROM Tabla1 WHERE ID=2;
#Desactivar modo seguro
SET SQL_SAFE_UPDATES=0;
UPDATE Tabla1 SET ASISTENCIA=0 WHERE GRUPO='GRUPO1';
SELECT *FROM Tabla1;
#Agregar columna
ALTER TABLE Tabla1 ADD Faltas TEXT;
SELECT *FROM Tabla1;














