version: '3'
services:
  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: neo4j/test

  python-app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - neo4j
