#Contenedores de servicio
services:
#Etiqueta para el contenedor 1
  imagen1:
    image: nginx:alpine
    ports: 
      - 8080:80
    volumes:
      - ./html:/usr/share/nginx/html
#Etiqueta para el contenedor 2
  imagen2:
    image: nginx:alpine
    ports: 
      - 8081:80
    volumes:
      - ./html2:/usr/share/nginx/html
