USE EJEMPLO;
CREATE TABLE EMPLEADOS(
	EMPID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE1 VARCHAR(100),
    APELLIDO VARCHAR(100),
    GENERO VARCHAR(100),
    NACIMIENTO DATE NOT NULL
);

CREATE TABLE UBICACIONES(
	UBIID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE2 VARCHAR(100),
    ESTADO VARCHAR(100)
);

INSERT INTO EMPLEADOS(NOMBRE1, APELLIDO, GENERO, NACIMIENTO)
VALUES
	('Sahin','Tenar','M', DATE '1984-01-09'),
	('cali', 'Devi', 'M', DATE '1989-03-26'),
  	('Joel','Roota','F', DATE '1948-11-29'),
	('Moe', 'Alister', 'F', DATE '1959-04-16');
INSERT INTO UBICACIONES(NOMBRE2, ESTADO)
VALUES ('SALA','BUENO'), ('COMEDOR', 'MALO'), ('PLANTA','BUENO');

#Combinación de campos
CREATE VIEW RESUMEN AS SELECT NOMBRE1, ESTADO, GENERO
	FROM EMPLEADOS,UBICACIONES;
SELECT * FROM RESUMEN;

SELECT NOMBRE2, NOMBRE1
	FROM EMPLEADOS, UBICACIONES
	GROUP BY NOMBRE2, NOMBRE1;

CREATE TABLE RESUMEN3(
    NOMBRE3 VARCHAR(100),
    NOMBRE4 VARCHAR(100)
);
#Evitar ambiguedades NombreTabla.NombreCampo
INSERT INTO RESUMEN3
SELECT UBICACIONES.NOMBRE2, EMPLEADOS.NOMBRE1 FROM UBICACIONES, EMPLEADOS;

SELECT * FROM RESUMEN3

