USE NOMBREBD;
CREATE TABLE ALUMNOS (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(10) NOT NULL,
	APELLIDO VARCHAR(10) NOT NULL
);

CREATE TABLE SALONES (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	GRUPO VARCHAR(10) NOT NULL,
	UBICACION VARCHAR(10) NOT NULL
);

#Agregar campo IDSALON.
ALTER TABLE ALUMNOS ADD COLUMN IDSALON INT NOT NULL AFTER ID;
#Definir la llave Foranea, enlazar con la tabla salones
#y establecer el mecanismo de actualización
ALTER TABLE ALUMNOS ADD CONSTRAINT FK_IDESALON FOREIGN KEY (IDSALON)
REFERENCES SALONES (ID) ON DELETE CASCADE ON UPDATE CASCADE;

#Agregar registros
#ID no se agrega, ya que, es autoincremental
INSERT INTO SALONES (GRUPO, UBICACION) VALUES ('A', 'PISO 1'), ('B','CANCHA');
#Consulta 
SELECT * FROM SALONES;

INSERT INTO ALUMNOS (NOMBRE, APELLIDO, IDSALON) VALUES ('CESAR', 'MOSQUERA', 1),
	   ('MIGUEL', 'AGUILAR', 1), ('PEDRO', 'MORENO', 2), ('PANCHO', 'VILLA', 2);
#Consulta 
SELECT * FROM ALUMNOS;
#Borrar un registro
DELETE FROM SALONES WHERE ID=1;
SELECT * FROM SALONES;
SELECT * FROM ALUMNOS;
#Actualizar
UPDATE SALONES SET ID=20 , GRUPO='C' WHERE ID=2;
SELECT * FROM SALONES;
SELECT * FROM ALUMNOS;                        
                        
                        
                        
DROP TABLE SALONES
