version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_HH
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=pruebaHH
      - MYSQL_ROOT_PASSWORD=Contrasena123$
    ports:
      - '3305:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local

